target:
  db: ARTICLE_DB
  tbl: ARTICLE_TABLE
  key: ARTICLE_KEY
  texts:
    - title
    - article
  where_condition:
    # - TD_INTERVAL(time,'-1d','JST')

tokenize_ja:
  col_text: normalize_unicode(text,'NFKC') # normalize_unicode(text,'NFKC')
  stopwords: "NULL"
  stoptags: stoptags_exclude(array("名詞-一般","名詞-固有名詞"))
  num_om_words: 30

interest_words:
  check: true
  db: WEBLOG_DB
  tbl: WEBLOG_TBL
  span: 180
  user_id: td_ms_id
  key: ARTICLE_KEY
  num_om_words: 30
