time_zone: JST

web:
  web:
    media_name: web
    # Pageviwe設定
    db: YOUR_WEB_LOG_DATABASE #set web_log database
    tbl: YOUR_WEB_LOG_TABLE #set web_log table
    key_id: KEY_ID #td_ssc_id or td_client_id
    date_range: 360

count_sum_max:
#  - output: ltv
#    func: SUM # SUM / COUNT / MAX
#    val: price
#    null_check_col: price
#    id: KEY_ID
#    db: YOUR_DATABASE
#    tbl: YOUR_TABLE
#    where_condition: 
#      #- TD_INTERVAL(time,'-360d','JST')

pivot:
#  - output: td_hour
#    key: CAST(TD_TIME_FORMAT(time,'HH','JST') AS INT)
#    value: COUNT(*)
#    null_check_col: time
#    id: KEY_ID
#    db: YOUR_DATABASE
#    tbl: YOUR_TABLE
#    where_condition: 
#      - TD_INTERVAL(time,'-360d','JST')
#    config:
#      - key: key = 0
#        col: 0
#      - key: key = 1
#        col: 1

true_false:
#  - output: td_tf
#    true_key: CAST(TD_TIME_FORMAT(time,'MM','JST') AS INT) BETWEEN 2 AND 5
#    null_check_col: time
#    id: KEY_ID
#    db: YOUR_DATABASE
#    tbl: YOUR_TABLE
#    where_condition: 
#      - TD_INTERVAL(time,'-360d','JST')

array:
#  - output: product_name
#    target: product_name
#    null_check_col: time
#    id: KEY_ID
#    db: YOUR_DATABASE
#    tbl: YOUR_TABLE
#    where_condition: 
#      - TD_INTERVAL(time,'-360d','JST')
