SELECT 
  * 
FROM (
  VALUES 
    ('time', 'UNIXタイム', '1617807600') 
    , ('td_url', 'URL', NULL) 
    , ('td_charset', '文字コード', 'utf-8')
    , ('td_description', 'ディスクリプション', NULL)
    , ('td_browser_version', 'ブラウザバージョン', '89.0.4389') 
    , ('td_os', 'OS', 'Windows') 
    , ('td_ip', 'IPアドレス', '11.11.111.111') 
    , ('td_browser', 'ブラウザ情報', 'Mobile Safari') 
    , ('td_referrer', 'リファラURL', 'https://yahoo.co.jp/') 
    , ('td_version', 'td_js_sdkバージョン', '2.5.0') 
    , ('td_title', 'サイトタイトル', NULL) 
    , ('td_language', 'PC言語設定', 'ja-jp') 
    , ('td_color', 'モニター色彩情報', '32-bit') 
    , ('td_os_version', 'OSバージョン', '11.1.0') 
    , ('td_user_agent', 'ユーザーエージェント', 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/152.1.363973642 Mobile/15E148 Safari/604.1') 
    , ('td_platform', 'プラットフォーム', 'Win32') 
    , ('td_host', 'URLホスト', 'www.hoge.co.jp') 
    , ('td_path', 'URLパス', '/article/') 
    , ('td_screen', 'スクリーンサイズ', '800x600') 
    , ('td_client_id', '1st Party cookie(Docment Cookie)', NULL) 
    , ('td_global_id', '3rd Party cookie(Docment Cookie)', NULL) 
    , ('td_ssc_id', '1st Party cookie(Server Side Cookie)', NULL) 
    , ('media_name', 'サイトソース名', '480x790') 
    , ('td_data_type', 'pageview/click ログタイプ', NULL) 
    , ('access_date_time', 'アクセス日時 yyyy-MM-dd HH:mm:ss', NULL) 
    , ('access_date', 'アクセス日 yyyy-MM-dd', NULL) 
    , ('access_hour', 'アクセス時 HH', NULL) 
    , ('week', '週番号', NULL) 
    , ('dow', '曜日', NULL) 
    , ('ampm', '午前午後', NULL) 
    , ('session_start_time', 'セッション開始UNIXTIME', NULL) 
    , ('session_end_time', 'セッション終了UNIXTIME', NULL) 
    , ('session_id', 'セッションID', NULL) 
    , ('session_num', 'セッション番号', NULL) 
    , ('browsing_sec', '滞在時間（秒）', NULL) 
    , ('td_cookie', '正規化したCookie（td_ssc_id/td_client_id/td_global_id）', NULL) 
    , ('td_cookie_type', '正規化したCookieタイプ（td_ssc_id/td_client_id/td_global_id）', NULL) 
    , ('user_id', 'ユーザーID', NULL) 
    , ('user_id_comp', 'セッション途中でログインした場合の補完', NULL) 
    , ('utm_campaign', 'UTMキャンペーン', NULL) 
    , ('utm_medium', 'UTMメディア', NULL) 
    , ('utm_source', 'UTMソース', NULL) 
    , ('utm_term', 'UTMターム', NULL) 
    , ('td_source_medium', 'ソース/メディア', NULL) 
    , ('td_source', 'UTMがある場合UTMを採用し、無い場合はリファラ', NULL) 
    , ('td_medium', 'UTMがある場合UTMを採用し、無い場合はリファラ', NULL) 
    , ('td_ref_host', 'リファラアドレスのホスト', NULL) 
    , ('article_key', 'td_host/td_pathを結合', NULL) 
    , ('ua_os', 'ユーザーエージェントから取得したOS', NULL) 
    , ('ua_vendor', 'ユーザーエージェントから取得したベンダー', NULL) 
    , ('ua_os_version', 'ユーザーエージェントから取得したOSバージョン', NULL) 
    , ('ua_browser', 'ユーザーエージェントから取得したブラウザ名', NULL) 
    , ('ua_category', 'ユーザーエージェントから取得したPC/スマホ', NULL) 
    , ('ip_country', 'IPアドレスから取得した国名', NULL) 
    , ('ip_prefectures', 'IPアドレスから取得した都道府県名', NULL) 
    , ('ip_city', 'IPアドレスから取得した都市名 - 利用非推奨', NULL) 
    , ('td_proc_date', 'アグリゲート処理実行日', NULL) 
    , ('td_viewport', 'ビューポイントサイズ', NULL) 
    --追加がある場合以下に記入
    --入力例：, ('カラム名', '説明') 
    --, ('', '', '') 
) as cols(col_name, col_info, sample)
