---
media:
  sample1:
    media_name: sample1
    master_segment_id:  # 初回データ作成時など、Master Segmentの更新をしない場合は空白
    output_db: td_master_segments
    master_table_recovery: false
    as_period: 365
    recovery:
      db: USER_MST_DB
      tbl: USER_MST_TBL
      key: USER_ID_COL
    # WebLog設定
    check_web: true
    key_id_web: td_cookie
    set_td_url_web: "'Web | '||td_title"
    engagement_vols_web: td_path 
    weblog_db: l1_sample #set web_log database
    weblog_tbl: sample_weblog #set web_log table
    where_condition_web:
      condition:
        #- session_num = 1
    # AppLog設定
    check_app: false
    key_id_app: td_uid
    set_td_url_app: "'App | '||event"
    engagement_vols_app: event 
    applog_db: l1_sample #set web_log database
    applog_tbl: sample_applog #set web_log table
    where_condition_app:
      condition:
    # エンゲージメントスコア設定
    add_engagement_calc:
      sql: 
        #- SUM(purchase_price) AS purchase_price_total      
